backend:
  name: git-gateway
  branch: main # or your default branch name

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
